# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.showLogsButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLogsButton.setFont(font)
        self.showLogsButton.setObjectName("showLogsButton")
        self.horizontalLayout.addWidget(self.showLogsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.gridWidget)
        self.label_1.setMaximumSize(QtCore.QSize(352, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.suspiciousTraficButton = QtWidgets.QRadioButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.suspiciousTraficButton.setFont(font)
        self.suspiciousTraficButton.setChecked(False)
        self.suspiciousTraficButton.setObjectName("suspiciousTraficButton")
        self.verticalLayout.addWidget(self.suspiciousTraficButton)
        self.noFiltrationButton = QtWidgets.QRadioButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.noFiltrationButton.setFont(font)
        self.noFiltrationButton.setChecked(True)
        self.noFiltrationButton.setObjectName("noFiltrationButton")
        self.verticalLayout.addWidget(self.noFiltrationButton)
        self.onlyWarningsButton = QtWidgets.QRadioButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.onlyWarningsButton.setFont(font)
        self.onlyWarningsButton.setChecked(False)
        self.onlyWarningsButton.setObjectName("onlyWarningsButton")
        self.verticalLayout.addWidget(self.onlyWarningsButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.interfacesList = QtWidgets.QListWidget(self.gridWidget)
        self.interfacesList.setObjectName("interfacesList")
        self.horizontalLayout_3.addWidget(self.interfacesList)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridWidget, 4, 0, 1, 1)
        self.gridWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pcapModeButton = QtWidgets.QRadioButton(self.gridWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pcapModeButton.setFont(font)
        self.pcapModeButton.setObjectName("pcapModeButton")
        self.gridLayout_4.addWidget(self.pcapModeButton, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.liveCaptureButton = QtWidgets.QRadioButton(self.gridWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.liveCaptureButton.setFont(font)
        self.liveCaptureButton.setObjectName("liveCaptureButton")
        self.gridLayout_4.addWidget(self.liveCaptureButton, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridWidget_2)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gridWidget_2, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конфигурация снифера"))
        self.runButton.setText(_translate("MainWindow", "Запуск"))
        self.showLogsButton.setText(_translate("MainWindow", "Показать логи"))
        self.label_1.setText(_translate("MainWindow", "Режим отображения:"))
        self.suspiciousTraficButton.setText(_translate("MainWindow", "Только подозрительный трафик"))
        self.noFiltrationButton.setText(_translate("MainWindow", "Без фильтрации"))
        self.onlyWarningsButton.setText(_translate("MainWindow", "Только предупреждения"))
        self.pcapModeButton.setText(_translate("MainWindow", "Чтение pcap-file"))
        self.label_2.setText(_translate("MainWindow", "Режим запуска:"))
        self.liveCaptureButton.setText(_translate("MainWindow", "Захват трафика"))

